### ISSUE TITLE
why the app consumes a lot of cpu resource and ram memory?

### ISSUE THREAD

**Issue by bachig26** [JorrinKievit/restreamer#11]
## Summary

https://github.com/JorrinKievit/restreamer/assets/96393348/2844437f-5ba2-46c6-909c-f002608a2355

as seen in the clip, this just one of a better times, and some time i can see the cpu usage goes up by 50% and ram usage goes up by 500 to 800 mb just while opening a title or refetching the sources.

**Comment by JorrinKievit** [comment]
Hmm I can't seem to reproduce the numbers you are mentioning. Overall, Electron is just very memory-hungry. It is kinda hard to optimize. I indeed see spikes when loading the sources, to around 10% CPU/500MB memory. 

When we think about it that seems normal. When a title is opened, the app starts requesting a lot of different sites (10+) simultaneously. Almost all sites are scraped by loading the requested HTML pages in memory and retrieving the needed data using regex. When this all happens at the same time, it makes sense that these values spike.

An alternative could be to request the sources one by one, instead of all at the same time. However, this will significantly slow down the retrieval of sources, which is also not desirable. I wouldn't know another good solution to improve performance a bit. I think the issue is more with Electron not being the most performant solution out there 😛
